#' Kaplan Meijer plot for patient subgroups.
#'
#' `plotSurvCategory()` generates an annotated KM-plot and shows either the univariate HR (two groups) or logtest p-value (more groups).
#'
#' @param in.df Input dataframe
#' @param survCol Column containing the survival object generated by Surv(). Can be either the name as a string or the column number.
#' @param sigCol Column containing the patient groups. Can be either the name as a string or the column number.
#' @param title Character. Plot title. Defaults to the name of the "sigCol" column
#' @param ymin Numeric. The lowerbound value on the y-axis. Use this to emphasize differences.
#' @param showLegend Boolean. Add a legend to the plot?
#' @param colours Character vector of colours to use for the different patient groups.
#' @param linetypes Character vector of linetypes to use for the different patient groups.
#'
#' @return NULL
#'

plotSurvCategory<-function(in.df,survCol,sigCol,title=NA, ymin=0, showlegend=T, colours=NA, linetypes=1){
    in.df$signature <-factor(in.df[,sigCol])
    in.df$survival  <-in.df[,survCol]
    KaplanM<-survfit(survival~signature,  type="kaplan-meier", conf.type="log", data=in.df)


    nrcats=length(levels(in.df$signature))

    if(nrcats==2 & is.na(colours)){
        colours<-c("black","red")
    }else if(nrcats==3 & is.na(colours)){
        colours<-c("darkgreen","black","red")
    }else if(nrcats==3 & is.na(colours)){
        colours<-c("green3","darkgreen","darkred","red")
    }else if(is.na(colours)){
        colours<-RColorBrewer::brewer.pal(n=nrcats, name="Set1")
    }

    plot(KaplanM, xlim=c(0,5), col=colours, lty=linetypes, mark.time=T,xscale=365.25,ylim=c(ymin,1),las=1,xlab="years", cex.axis=1.5, cex.lab=1.5, cex.main=2.5, ylab=survCol)

    if(is.na(title)){title=sigCol}
    title(title, line=0.25)

    if(showlegend){
        leg = paste0(levels(factor(in.df[,sigCol])), " (n=",as.numeric( table(in.df[,sigCol]) ),")")
        legend(x="bottomleft", col=colours, lwd=2, lty=linetypes, cex=1.2,legend=leg, bty ="n")
    }

    if(nrcats==2){
        co <- summary(coxph(survival~signature,data=in.df))$coefficients[1,c(2,5)]
        ci <- summary(coxph(survival~signature,data=in.df))$conf.int[1,3:4]
        text(x=200,y=(0.2+showlegend/10)*(1-ymin)+ymin,labels=paste0("HR:",round(co[1],2)," (",round(ci[1],2),"-",round(ci[2],2),")"),cex = 1.2,adj=0)
        text(x=200,y=(0.13+showlegend/10)*(1-ymin)+ymin,labels=paste0("p=",round(co[2],floor(-log10(co[2]))+2)),cex = 1.2,adj=0)
    }else{
        logtestp<-summary(coxph(survival~signature,data=in.df))$logtest["pvalue"]
        text(x=200,y=(0.1+showlegend/5)*(1-ymin)+ymin,labels=paste0("logtest p=",round(logtestp,floor(-log10(logtestp))+2)),cex = 1.2,adj=0)
    }

}
