#' Kaplan Meijer plot for continuous variable.
#'
#' `plotQuantileSplit()` splits a patient group into n subgroups and generates an annotated KM-plot. It shows either the univariate HR (two groups) or logtest p-value (more groups).
#'
#' @param in.df Input dataframe
#' @param survCol Column containing the survival object generated by Surv(). Can be either the name as a string or the column number.
#' @param sigCol Column containing the continuous variable. Can be either the name as a string or the column number.
#' @param nrsplits Numeric. Into how many quantiles should the variable be split?
#' @param ... Additional arguments to plotSurvCategory
#'
#' @return NULL
#'

plotQuantileSplit<-function(in.df,survCol,sigCol,nrsplits=4, ...){
    # note: removed "plot_title" argument, replace with "title" which will be passed to PlotSurvCategory through the ... argument.

    qq <-quantile(in.df[,sigCol], probs=seq(0,1, by=1/nrsplits), na.rm=TRUE)
    qq <-unique(qq)
    nrsplits=length(qq)-1

    if(nrsplits==3){
        lab=c("Low","Medium","High")
    }else if(nrsplits==4){
        lab=c("Very Low","Low","High","Very High")
    }else{
        lab<-paste0("Quantile",1:nrsplits)
    }

    if(nrsplits<2){
        in.df$Split<-factor(ifelse(in.df[,sigCol]>qq[1], paste0("Over",qq[1]),paste0("Under",qq[1])))
    }else{
        in.df$Split<-factor(cut(in.df[,sigCol], labels=lab,breaks=qq,include.lowest=TRUE),levels=lab)
    }

    #if(is.na(plot_title)){plot_title = paste0(sigCol,"_",survCol)}

    plotSurvCategory(in.df,survCol=survCol,sigCol="Split", ...)
}
